added info on the DevOps concepts
learntocloud/learn-to-cloud pull request #137
Opened 2023-03-17 19:36 UTC by rishabkumar7

2023-03-17 19:38 UTC, madebygps approved these changes
lgtm

2023-04-05 16:34 UTC, shivam-sharma7 requested changes

2023-04-05 16:34 UTC, shivam-sharma7 commented on docs/phase4/README.md
> +Feel free to spend as much time as you'd like, people have asked for a timeline and breakdown so I've added it. Every DevOps practice matters, but these are the most used on an entry/junior level. Yo
It would be better to remove extra line.

2023-04-12 14:19 UTC, madebygps commented
hi @shivam-sharma7 those lines are for markdown formatting.
@rishabkumar7 please merge your changes only today.

2023-04-12 16:21 UTC, merged

2023-04-13 00:20 UTC, shivam-sharma7 commented
okay @madebygps