Spanish translation
learntocloud/learn-to-cloud pull request #41
Opened 2022-05-27 06:02 UTC by azgcloudev

welcome section

2022-05-31 15:56 UTC, rishabkumar7 requested changes
I don't believe we need contributors(es/Contributors.md) in translations, could we revert that.

2022-06-01 05:20 UTC, azgcloudev reviewed
changed made about contributors site

2022-06-05 13:02 UTC, madebygps approved these changes

2022-06-05 13:03 UTC, madebygps commented
The translation looks great :) thank you @azgcloudev 

@rishabkumar7 looks like there is a conflict with some config stuff in _navbar and index.html. Can you resolve it and then merge changes please :)

2022-06-06 18:15 UTC, merged